export const OPEN_FILTERS = "OPEN_FILTERS";
export const CLOSE_FILTERS = "CLOSE_FILTERS";
export const UPDATE_HASREWARD_VALUE = "SAVE_HAS_REWARD";
export const UPDATE_SEARCHBAR_VALUE = "UPDATE_SEARCHBAR_VALUE";
export const UPDATE_REWARD_VALUE = "UPDATE_REWARD_VALUE";
export const UPDATE_TYPE_VALUE = "UPDATE_TYPE_VALUE";
export const UPDATE_DISTANCE_VALUE = "UPDATE_DISTANCE_VALUE"