export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";
export const ADD_INFORMATION_OPEN = "ADD_INFORMATION_OPEN";
export const SHOW_INFORMATION_OPEN = "SHOW_INFORMATION_OPEN";
export const EDIT_INFORMATION_OPEN = "EDIT_INFORMATION_OPEN";
