export const SIDECONTENT_OPEN = "SIDECONTENT_OPEN";
export const SIDECONTENT_CLOSE = "SIDECONTENT_CLOSE";
export const REPORTCARD_CLICK = "REPORTCARD_CLICK"
export const MAPCARD_CLOSE = "MAPCARD_CLOSE";
export const MAPCARD_OPTIONS_EXPAND = "MAPCARD_OPTIONS_EXPAND";
export const MAPCARD_OPTIONS_CLOSE = "MAPCARD_OPTIONS_CLOSE";
export const SIDEBAR_BUTTON_CLICK = "SIDEBAR_BUTTON_CLICK";